# Generated by Django 4.1 on 2022-08-27 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watchlist_app', '0003_watchlist_platform'),
    ]

    operations = [
        migrations.AlterField(
            model_name='streamplatform',
            name='name',
            field=models.CharField(max_length=35),
        ),
    ]
