# Generated by Django 4.1 on 2022-08-28 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watchlist_app', '0004_alter_streamplatform_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='streamplatform',
            name='name',
            field=models.CharField(max_length=30),
        ),
    ]
